apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ovoa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kejy-tenant/rhtap-demo-app/hacbs-test-project-ovoa@sha256:0a58dc9be71224a04120c8468710014b33a3173e9674ce87f197bbdf5b43c277
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
