apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ovoa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ovoa
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ovoa
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ovoa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ovoa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kejy-tenant/rhtap-demo-app/hacbs-test-project-ovoa@sha256:0a58dc9be71224a04120c8468710014b33a3173e9674ce87f197bbdf5b43c277
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
